name: 'Terraform'

on:
  
  workflow_dispatch:


env:
  ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
  ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
  ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}


jobs:
  terraform:
    name: 'Terraform Execution'
    runs-on: ubuntu-latest
    environment: production

    steps:
      
    - name: Checkout
      uses: actions/checkout@v2

    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

   
    - name: Terraform Init
      run: terraform init
     
    - name: Terraform Plan
      run: terraform plan 

    - name: terraform Apply
      run: terraform apply -auto-approve
    
    
    
    
    
    
