name: 'Terraform-Powershell'

on:
  push:
    branches: [ "main" ]
#   pull_request:
#   workflow-dispatch:
#     input: 

env:
  ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
  ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
  ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}


   

jobs:

 
  # terraform:
  #   name: 'Terraform Execution'
  #   runs-on: ubuntu-latest
  #   environment: production

   
  #   defaults:
  #     run:
  #       shell: bash

  #   steps:
      
  #   - name: Checkout
  #     uses: actions/checkout@v2

    
  #   - name: Setup Terraform
  #     uses: hashicorp/setup-terraform@v1
  #     with:
  #       cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

   
  #   - name: Terraform Init
  #     run: terraform init
     
  #   - name: Terraform Plan
  #     run: terraform plan 

  #   - name: terraform Apply
  #     run: terraform apply -auto-approve
      
      
  powershell_script:
    name: 'Powershell Script Execution'
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 

    - name: Run PowerShell script
      run: powershell -File ./scripts/script1.ps1
      id: powershell

    - name: Save output to CSV
      run: |
        $output = "${{ steps.powershell.outputs.output }}"
        $output | ConvertFrom-Json | Export-Csv output.csv -NoTypeInformation

    - name: Upload CSV artifact
      uses: actions/upload-artifact@v2
      with:
        name: script-output
        path: output.csv

   

    
    
    
    
    
    
