name: 'Powershell'

on:
  workflow_dispatch:
    
jobs:
   powershell_script:
    name: 'Powershell Script Execution'
    runs-on: ubuntu-latest
    environment: production

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 

    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
       inlineScript: |
          
          
          $output=@()
          # PowerShell script content here
          $allVms = Get-AzVM

          # Iterate through each VM and retrieve its details
          foreach($vm in $allVms) {
              $vmName = $vm.Name
              $resourceGroupName = $vm.ResourceGroupName

              # Get the VM details
              $vmDetails = Get-AzVM -ResourceGroupName $resourceGroupName -Name $vmName

              # Output the VM details
              Write-Output "VM Name: $($vmDetails.Name)"
              Write-Output "Location: $($vmDetails.Location)"
              
              Write-Output "Resource Group Name: $resourceGroupName"
              
              Write-Output "Status: $($vmDetails.status)"
              
          }
          $outout | FT
          Write-Output $output > output.txt

          
       azPSVersion: "latest"

    - name: Save output as artifact
      uses: actions/upload-artifact@v2
      with:
         name: Workflow Output
         path: output.txt