name: 'Powershell'

on:
  push:
    branches: [ "main" ]
    
jobs:
   powershell_script:
    name: 'Powershell Script Execution'
    runs-on: ubuntu-latest
    environment: production

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 

    - name: Run PowerShell script
      run: powershell -File ./scripts/script1.ps1
      id: powershell

    - name: Save output to CSV
      run: |
        $output = "${{ steps.powershell.outputs.output }}"
        $output | ConvertFrom-Json | Export-Csv output.csv -NoTypeInformation

    - name: Upload CSV artifact
      uses: actions/upload-artifact@v2
      with:
        name: script-output
        path: output.csv