name: 'Powershell'

on:
  push:
    branches: [ "main" ]
    
jobs:
   powershell_script:
    name: 'Powershell Script Execution'
    runs-on: windows-latest
    environment: production

    
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 

    - name: Run Azure PowerShell Script File
      uses: azure/powershell@v1
      id: step1
      with:
        inlineScript: #./scripts/script1.ps1 
            | 
            $Result = @()
            #Get all Resource groups
            $AllRGs = Get-AzResourceGroup
            $TotalGroups = $AllRGs.Count
            $i = 1 
            ForEach ($RG in $AllRGs) {
            Write-Progress -Activity "Processing $($RG.ResourceGroupName)" -Status "$i out of $TotalGroups Resource groups completed"
            #Fetch virtual machines in the group
            $VMList = Get-AzVM -ResourceGroupName $RG.ResourceGroupName -Status
              
            ForEach ($VM in $VMList) {
            $Result += New-Object PSObject -property $([ordered]@{ 
            VMName = $VM.Name
            VMStatus  = $VM.PowerState
            ProvisioningState = $VM.ProvisioningState
            ResourceGroup = $VM.ResourceGroupName
            Location = $VM.Location
            })
            }
            $i++
            }
            $Result | FT # alias Format Table
             #"output=$Result" >> $env:GITHUB_OUTPUT
            Write-Output $Result | Export-CSV -Path "C:/AllAzureVMStatus.CSV" -NoTypeInformation -Encoding UTF8
        azPSVersion: "latest"
       # run: Write-Output ${{ steps.step1.outputs.output }} >> abc.csv
    
