name: 'Powershell'

on:
  workflow_dispatch:
    
jobs:
   powershell_script:
    name: 'Powershell Script Execution'
    runs-on: windows-latest
    environment: production

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 

    
    - name: Run PowerShell script
      shell: pwsh
      run: |
          # # Replace script-content with the content of your PowerShell script
          # $scriptContent = @"
          # # PowerShell script content here
          
          # $Result = @()
          # #Get all Resource groups
          # $AllRGs = Get-AzResourceGroup
          # $TotalGroups = $AllRGs.Count
          # $i = 1 
          # ForEach ($RG in $AllRGs) {
          # Write-Progress -Activity "Processing $($RG.ResourceGroupName)" -Status "$i out of $TotalGroups Resource groups completed"
          # #Fetch virtual machines in the group
          # $VMList = Get-AzVM -ResourceGroupName $RG.ResourceGroupName -Status
            
          # ForEach ($VM in $VMList) {
          # $Result += New-Object PSObject -property $([ordered]@{ 
          # VMName = $VM.Name
          # VMStatus  = $VM.PowerState
          # ProvisioningState = $VM.ProvisioningState
          # ResourceGroup = $VM.ResourceGroupName
          # Location = $VM.Location
          # })
          # }
          # $i++
          # }
          # $Result | FT

          # "@
          # echo $scriptContent > script.ps1
          pwsh -File ./scripts/script1.ps1


    # - name: Upload CSV artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: script-output
    #     path: output.txt