name: 'Terraform deployment to Azure'

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
  ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
  ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
  ROOT_PATH: '${{github.workspace}}' 

jobs:
  terraform:
    name: 'Terraform plan'
    runs-on: ubuntu-latest
    environment: production

   
    defaults:
      run:
        shell: bash

    steps:
      # This will going to checkout our source code.
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
      working-directory: ${{env.ROOT_PATH}}


    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan 

    